version: '3'

services:
  backend:
    build: ./backend
    container_name: bachelors-backend
    restart: unless-stopped
    env_file: backend/.env.dev
    # environment:
    #   - MONGO_USERNAME=$MONGO_USERNAME
    #   - MONGO_PASSWORD=$MONGO_PASSWORD
    #   - MONGO_HOSTNAME=db
    #   - MONGO_PORT=$MONGO_PORT
    #   - MONGO_DB=$MONGO_DB 
    ports:
      - "3000:3000"