name: develop-ci-cd

on:
  push:
    branches:
      - dev-ci-cd

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, ubuntu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env
          cat .env

      - name: Run app
        run: docker compose up -d